name: Build and Deploy

on: [push]

jobs:
  build-deploy:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Tag Docker Image
        run: |
          docker build -t ghcr.io/naesalang/test-cicd .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/naesalang/test-cicd

      - name: Deploy on Server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Ensure repository name is lowercase
            sudo docker stop test-cicd || true
            sudo docker rm test-cicd || true
            sudo docker run -d --name test-cicd ghcr.io/naesalang/test-cicd
