on: [push]

jobs:
  build-deploy:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ghcr.io/naesalang/test-cicd .

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Push Docker image
        run: docker push ghcr.io/naesalang/test-cicd

      - name: Deploy on server
        run: |
          echo "${{ secrets.SSH_KEY }}" > ssh_key
          chmod 600 ssh_key
          ssh-keyscan -H ${{ secrets.HOSTNAME }} >> ~/.ssh/known_hosts
          ssh -i ssh_key ubuntu@${{ secrets.HOSTNAME }} "bash /home/ubuntu/deploy.sh"
